name: Build C# Solution

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest # Or ubuntu-latest, depending on your project's needs

    steps:
    - uses: actions/checkout@v4 # Checkout the repository code

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.x'

    - name: Restore dependencies
      run: dotnet restore 'Unisoc AT.sln'

    - name: Build solution
      run: dotnet build 'Unisoc AT.sln' --configuration Release

    - name: List some files 2
      # working-directory: tdlib_source/example/android
      run: find . -maxdepth 5
