name: Build C# Solution

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest # Or ubuntu-latest, depending on your project's needs

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4 # Checkout the repository code

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    # - name: Build solution
    #   run: dotnet build --configuration Release /p:Platform="Any CPU" /p:PreferredToolArchitecture=x64
    - name: Build with Visual Studio MSBuild
      run: dotnet build "Unisoc AT.sln" --configuration Release /p:Platform="Any CPU" /p:PreferredToolArchitecture=x64 /p:GenerateResourceMSBuildArchitecture=x64 /p:UseSharedCompilation=false

    - name: List some files
      # working-directory: tdlib_source/example/android
      run: dir

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: '**/bin/*'
