name: Build C# Solution

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest # Or ubuntu-latest, depending on your project's needs

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4 # Checkout the repository code

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build solution
      run: dotnet build --configuration Release /p:Platform="Any CPU" /p:PreferredToolArchitecture=x64

    - name: List some files 2
      # working-directory: tdlib_source/example/android
      run: find . -maxdepth 5
